/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment11;

import Classes.Shapes;
import Classes.Ellipse;
import Classes.Rectangle;
import Classes.Line;
import Classes.Polygon;
import com.sun.glass.ui.Size;
import java.awt.Graphics;
import java.awt.Point;
import static java.lang.Integer.parseInt;



/**
 *
 * @author taloh
 */
public class Assignment_11_PolymorphismUI extends javax.swing.JFrame {

    /**
     * Creates new form Assignment_11_PolymorphismUI
     */
    Shapes shape;
    
    public Assignment_11_PolymorphismUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        m_pnlSketchpad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m_tfWidth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        m_tfHeight = new javax.swing.JTextField();
        m_btnRectangle = new javax.swing.JToggleButton();
        m_btnEllipse = new javax.swing.JToggleButton();
        m_btnLine = new javax.swing.JToggleButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel1.setText("Sketchpad");

        m_pnlSketchpad.setBackground(new java.awt.Color(153, 153, 255));
        m_pnlSketchpad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(102, 102, 255)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 255), new java.awt.Color(102, 0, 255))));
        m_pnlSketchpad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_pnlSketchpadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout m_pnlSketchpadLayout = new javax.swing.GroupLayout(m_pnlSketchpad);
        m_pnlSketchpad.setLayout(m_pnlSketchpadLayout);
        m_pnlSketchpadLayout.setHorizontalGroup(
            m_pnlSketchpadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        m_pnlSketchpadLayout.setVerticalGroup(
            m_pnlSketchpadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel2.setText("How big do you want to draw your shape?");

        jLabel3.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jLabel3.setText("Width:");

        jLabel5.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jLabel5.setText("Height:");

        m_tfWidth.setText("0");
        m_tfWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tfWidthActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel6.setText("What kind of shape do you want to draw?");

        m_tfHeight.setText("0");
        m_tfHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tfHeightActionPerformed(evt);
            }
        });

        m_btnRectangle.setBackground(new java.awt.Color(102, 102, 255));
        m_btnRectangle.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_btnRectangle.setForeground(new java.awt.Color(255, 255, 255));
        m_btnRectangle.setText("Rectangle");

        m_btnEllipse.setBackground(new java.awt.Color(102, 102, 255));
        m_btnEllipse.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_btnEllipse.setForeground(new java.awt.Color(255, 255, 255));
        m_btnEllipse.setText("Ellipse");

        m_btnLine.setBackground(new java.awt.Color(102, 102, 255));
        m_btnLine.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_btnLine.setForeground(new java.awt.Color(255, 255, 255));
        m_btnLine.setText("Line");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1)
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(m_tfHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(m_tfWidth)))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(m_btnRectangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_btnEllipse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_btnLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(m_pnlSketchpad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_pnlSketchpad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)
                        .addComponent(m_btnRectangle)
                        .addGap(18, 18, 18)
                        .addComponent(m_btnEllipse)
                        .addGap(18, 18, 18)
                        .addComponent(m_btnLine)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(m_tfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(m_tfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_tfHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tfHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_tfHeightActionPerformed

    private void m_tfWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tfWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_tfWidthActionPerformed

    private void m_pnlSketchpadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_pnlSketchpadMouseClicked
        Point ulc = evt.getPoint();
        Size size = new Size();
        size.width = parseInt(m_tfWidth.getText());
        size.height = parseInt(m_tfHeight.getText());
        Graphics g = m_pnlSketchpad.getGraphics();
        
        if (m_btnRectangle.isSelected()){
            shape = new Rectangle(size.width, size.height);
        }
        else if (m_btnEllipse.isSelected()){
            shape = new Ellipse(size.width, size.height);
        }
        else if (m_btnLine.isSelected()){
            shape = new Line(size.width, size.height);
        }
        //else if (m_btnStar.isSelected()){
            //int x;
            //int y;
            //int z;
            //shape = new Polygon(y, z, x);
        //}
        if (shape != null){
            shape.Draw(g, ulc.x, ulc.y);
        }
    }//GEN-LAST:event_m_pnlSketchpadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment_11_PolymorphismUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment_11_PolymorphismUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment_11_PolymorphismUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment_11_PolymorphismUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment_11_PolymorphismUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton m_btnEllipse;
    private javax.swing.JToggleButton m_btnLine;
    private javax.swing.JToggleButton m_btnRectangle;
    private javax.swing.JPanel m_pnlSketchpad;
    private javax.swing.JTextField m_tfHeight;
    private javax.swing.JTextField m_tfWidth;
    // End of variables declaration//GEN-END:variables
}
